### ISSUE TITLE
ERROR: Exception in ASGI application

### ISSUE THREAD

**Issue by t41372** [t41372/Open-LLM-VTuber#27]
> 朋友，你能把报错信息截的完整点吗... 截图里没有什么有效信息... 最上面那个 OS.Error 是什么？ 还有，你能不能新开一个 issue? 你这个问题跟这个issue 好像没有关系...

就是直接运行python server.py
```
python server.py
INFO:     Started server process [26252]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:12393 (Press CTRL+C to quit)
INFO:     ::1:12221 - "GET / HTTP/1.1" 200 OK
INFO:     ::1:12221 - "GET /libs/live2dcubismcore.min.js HTTP/1.1" 200 OK
INFO:     ::1:12220 - "GET /libs/live2d.min.js HTTP/1.1" 200 OK
INFO:     ::1:12236 - "GET /TaskQueue.js HTTP/1.1" 200 OK
INFO:     ::1:12234 - "GET /libs/pixi.min.js HTTP/1.1" 200 OK
INFO:     ::1:12235 - "GET /libs/index.min.js HTTP/1.1" 200 OK
INFO:     ::1:12237 - "GET /index.css HTTP/1.1" 200 OK
INFO:     ::1:12237 - "GET /libs/ort.js HTTP/1.1" 200 OK
INFO:     ::1:12236 - "GET /libs/bundle.min.js HTTP/1.1" 200 OK
INFO:     ::1:12235 - "GET /live2d.js HTTP/1.1" 200 OK
INFO:     ('::1', 12239) - "WebSocket /client-ws" [accepted]
INFO:     connection open
Connection established
Model Information Loaded.
Model Information Loaded.
C:\Users\loong\.conda\envs\nlp\lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py:35: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
C:\Users\loong\.conda\envs\nlp\lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py:253: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
2024-10-17 16:29:26,410 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Downloading: 100%|████████████████████████████████████████████████████████████████| 6.00k/6.00k [00:00<00:00, 12.9kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 116k/116k [00:00<00:00, 260kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 33.9kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 238k/238k [00:00<00:00, 478kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 368k/368k [00:00<00:00, 614kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.81k/1.81k [00:00<00:00, 5.07kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 396/396 [00:00<00:00, 1.08kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 56.1k/56.1k [00:00<00:00, 137kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 935k/935k [00:00<00:00, 1.23MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 56.5k/56.5k [00:00<00:00, 113kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 27.3k/27.3k [00:00<00:00, 66.1kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 893M/893M [00:20<00:00, 46.3MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 9.09k/9.09k [00:00<00:00, 27.3kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 880k/880k [00:00<00:00, 1.18MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 194k/194k [00:00<00:00, 381kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 318k/318k [00:00<00:00, 479kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 344k/344k [00:00<00:00, 487kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 30.5k/30.5k [00:00<00:00, 48.3kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 43.9k/43.9k [00:00<00:00, 85.8kB/s]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\middleware\errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 93, in app
    await func(session)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\fastapi\routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\server.py", line 61, in websocket_endpoint
    open_llm_vtuber = OpenLLMVTuberMain(self.open_llm_vtuber_config)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\main.py", line 69, in __init__
    self.asr = self.init_asr()
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\main.py", line 140, in init_asr
    asr = ASRFactory.get_asr_system(asr_model, **asr_config)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\asr\asr_factory.py", line 28, in get_asr_system
    return FunASR(
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\asr\fun_asr.py", line 29, in __init__
    self.model = AutoModel(
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\funasr\auto\auto_model.py", line 104, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\funasr\auto\auto_model.py", line 192, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable
INFO:     connection closed
INFO:     ::1:12237 - "GET /bg/cityscape.jpeg HTTP/1.1" 200 OK
INFO:     ::1:12237 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

_Originally posted by @lonngxiang in https://github.com/t41372/Open-LLM-VTuber/issues/18#issuecomment-2418902117_

**Comment by t41372** [comment]
看这个log 应该是 FunASR 没有办法初始化。可以给我看看你的 FunASR 的配置吗?
另外，我刚刚到 FunASR 的 repo 那边去看了一下，他们好像也有遇到类似的情况，有不少issue都有描述类似的问题。
你可以试试看https://github.com/modelscope/FunASR/issues/1810 这个issue提到的方案。

你可以在 `main.py` 顶部(在各种import的下面)加上
~~~py
os.environ['PYTORCH_JIT'] = '0'
~~~

**Comment by lonngxiang** [comment]
加了server.py，main.py，运行python server.py还是不行

2024-10-17 17:37:48,881 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\middleware\errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 93, in app
    await func(session)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\fastapi\routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\server.py", line 62, in websocket_endpoint
    open_llm_vtuber = OpenLLMVTuberMain(self.open_llm_vtuber_config)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\main.py", line 70, in __init__
    self.asr = self.init_asr()
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\main.py", line 141, in init_asr
    asr = ASRFactory.get_asr_system(asr_model, **asr_config)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\asr\asr_factory.py", line 28, in get_asr_system
    return FunASR(
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\asr\fun_asr.py", line 29, in __init__
    self.model = AutoModel(
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\funasr\auto\auto_model.py", line 104, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\funasr\auto\auto_model.py", line 192, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
TypeError: 'NoneType' object is not callable
INFO:     connection closed
INFO:     ::1:8660 - "GET /favicon.ico HTTP/1.1" 404 Not Found

**Comment by lonngxiang** [comment]
> FunASR

FunASR我今天单独运行是可以的

**Comment by lonngxiang** [comment]
> 什么叫单独运行 FunASR? 你在其他应用里有用到FunASR并成功运行了吗？ 可以给我看看你的 FunASR的配置吗? `(这几天回issue，忽然感觉人类跟LLM其实没啥区别，都是文字看到后面就忘了前面... 或许LLM的这种特性就是源自于人的这种特性...)`

就是单独其他应用使用funasr可以正常;
funasr                         1.0.19      

```
 from funasr import AutoModel
    model =AutoModel(model="paraformer-zh",  vad_model="fsmn-vad",  
                            #  punc_model="ct-punc",
                  # spk_model="cam++", 
                  )
```

**Comment by t41372** [comment]
可以给我看看你的 FunASR的配置吗?

**Comment by lonngxiang** [comment]
> 可以给我看看你的 FunASR的配置吗?
没怎么配置就是下面这样进行语音识别的
```
 from funasr import AutoModel

model =AutoModel(model="paraformer-zh",  vad_model="fsmn-vad",  
                            #  punc_model="ct-punc",
                  # spk_model="cam++", 
                  )

res = model.generate(input=audio_file, 
                     batch_size_s=600, hotword="小红小红"
                     )
print(res)
```

**Comment by t41372** [comment]
......
我指的是你在 Open-LLM-VTuber里面的 FunASR 的配置，在 `conf.yaml` 里面，你有动过吗？

**Comment by lonngxiang** [comment]
@t41372 另外我这边也写了份live2d的实时语音聊天简单案例，您可以看下代码  https://github.com/lonngxiang/live2d-talker

**Comment by lonngxiang** [comment]
> ...... 我指的是你在 Open-LLM-VTuber里面的 FunASR 的配置，在 `conf.yaml` 里面，你有动过吗？

简单改了下，ASR_MODEL:还是"FunASR"，然后模型更换了其他模型

**Comment by t41372** [comment]
你开issue的时候我就看过你的代码了，但我要先说明，我有很多用户用FunASR，他们都没有出任何问题，我自己日常使用用的也是FunASR，所以...
另外，你更换了什么模型？？那个代码不就是在初始化模型的时候炸的吗？你用 `paraformer-zh` 尝试过了吗？你有用预设的选项 `iic/SenseVoiceSmall` 试过能跑吗？
你不能一次就把话说完，把该提供的信息提供完吗... 抱歉语气有点冲... 我很乐意帮助别人，但我不喜欢在无意义的事情上浪费时间...

**Comment by lonngxiang** [comment]
> 你开issue的时候我就看过你的代码了，但我要先说明，我有很多用户用FunASR，他们都没有出任何问题，我自己日常使用用的也是FunASR，所以... 另外，你更换了什么模型？？那个代码不就是在初始化模型的时候炸的吗？你用 `paraformer-zh` 尝试过了吗？你有用预设的选项 `iic/SenseVoiceSmall` 试过能跑吗？ 你不能一次就把话说完，把该提供的信息提供完吗... 抱歉语气有点冲... 我很乐意帮助别人，但我不喜欢在无意义的事情上浪费时间...

conf.yaml里的funasr模型没有改，还是默认的iic/SenseVoiceSmall；不好意思没有一下get说清楚

**Comment by lonngxiang** [comment]
![image](https://github.com/user-attachments/assets/74fbf22e-3576-4e63-9932-6bf8c0245caf)

**Comment by t41372** [comment]
可以帮我把 Open-LLM-VTuber项目的 FunASR 设置下面的 `model_name`选项改成 `paraformer-zh` 试试看嘛？看看是 SenseVoiceSmall 在你的电脑上跑不起来还是其他地方出了问题。

**Comment by lonngxiang** [comment]
改成paraformer-zh重新执行，相关错误信息还行，另外的是llm配置问题，这边好像不支持openai的接口形式
```
Loading model cost 1.806 seconds.
DEBUG:jieba:Loading model cost 1.806 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
ckpt: C:\Users\loong\.cache\modelscope\hub\iic\punc_ct-transformer_cn-en-common-vocab471067-large\model.pt
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 242, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\middleware\errors.py", line 152, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 362, in handle
    await self.app(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 95, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\starlette\routing.py", line 93, in app
    await func(session)
  File "C:\Users\loong\.conda\envs\nlp\lib\site-packages\fastapi\routing.py", line 383, in app
    await dependant.call(**solved_result.values)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\server.py", line 62, in websocket_endpoint
    open_llm_vtuber = OpenLLMVTuberMain(self.open_llm_vtuber_config)
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\main.py", line 103, in __init__
    self.llm = self.init_llm()
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\main.py", line 124, in init_llm
    llm = LLMFactory.create_llm(
  File "C:\Users\loong\Downloads\Open-LLM-VTuber-main\Open-LLM-VTuber-main\llm\llm_factory.py", line 32, in create_llm
    raise ValueError(f"Unsupported LLM provider: {llm_provider}")
ValueError: Unsupported LLM provider: deepseek
INFO:     connection closed
INFO:     ::1:2698 - "GET /bg/cityscape.jpeg HTTP/1.1" 304 Not Modified
INFO:     ::1:2698 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

**Comment by t41372** [comment]
那个 LLM Provider 你目前只能填 `MemGPT` 或是 `ollama`。所有OpenAI格式的接口，都用 Ollama。

这个ollama，我很快会把名字改成 `openai-compatible` 或是类似的名字，避免混淆。他的底层实现就是用 OpenAI SDK 做的 (很久以前不是，所以名字用的是 Ollama)。

我这里提供了那部分设置的注释的中文翻译

<img width="623" alt="Screenshot 2024-10-17 at 6 36 03 PM" src="https://github.com/user-attachments/assets/680c01e8-917f-4768-8683-83b7450eba65">

**Comment by lonngxiang** [comment]
现在换成paraformer-zh和使用ollama运行起来了
![image](https://github.com/user-attachments/assets/678d7e06-190d-4959-885d-e2a483b09876)

**Comment by lonngxiang** [comment]
非常感谢耐心的解答，是个很好的项目

**Comment by xl-1314520** [comment]
![屏幕截图 2024-11-13 213816](https://github.com/user-attachments/assets/9a27056b-f239-4d5d-862c-31dc4e0d5b97)
为什么我改了model_name但不行
