### ISSUE TITLE
 No module named 'onnxconverter_common'

### ISSUE THREAD

**Issue by xfrqh** [t41372/Open-LLM-VTuber#61]
版本：0.5.2

复现流程：
1. 下载`0.5.2`的整合包
2. 在项目根目录执行`python start_webui.py`。报错` No module named 'onnxconverter_common'`
3. 在项目根目录执行`activate_conda.py`，输入` pip install onnx`
4.  在项目根目录执行`python start_webui.py`。依然报错` No module named 'onnxconverter_common'`

```shell
PS C:\RJ\Abao\Open-LLM-VTuber> python start_webui.py
2024-12-22 17:50:22.701 | INFO     | __main__:__init__:38 - t41372/Open-LLM-VTuber, version 0.5.2
2024-12-22 17:50:22.701 | INFO     | __main__:__init__:59 - Preloading ASR and TTS models...
2024-12-22 17:50:22.702 | INFO     | __main__:__init__:60 - Using: FunASR
2024-12-22 17:50:22.702 | INFO     | __main__:__init__:63 - Using: edgeTTS
Traceback (most recent call last):
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 598, in <module>
    server = WebSocketServer(open_llm_vtuber_main_config=config)
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 68, in __init__
    self.model_manager.initialize_models()
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 474, in initialize_models
    self._init_asr()
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 484, in _init_asr
    self.cache.set("asr", ASRFactory.get_asr_system(asr_model, **asr_config))
  File "C:\RJ\Abao\Open-LLM-VTuber\asr\asr_factory.py", line 26, in get_asr_system
    from .fun_asr import VoiceRecognition as FunASR
  File "C:\RJ\Abao\Open-LLM-VTuber\asr\fun_asr.py", line 6, in <module>
    from funasr import AutoModel
  File "C:\RJ\Abao\Open-LLM-VTuber\conda\envs\open_llm_vtuber\lib\site-packages\funasr\__init__.py", line 39, in <module>
    from funasr.auto.auto_model import AutoModel
  File "C:\RJ\Abao\Open-LLM-VTuber\conda\envs\open_llm_vtuber\lib\site-packages\funasr\auto\auto_model.py", line 30, in <module>
    from funasr.utils import export_utils
  File "C:\RJ\Abao\Open-LLM-VTuber\conda\envs\open_llm_vtuber\lib\site-packages\funasr\utils\export_utils.py", line 5, in <module>
    from onnxconverter_common import float16
ModuleNotFoundError: No module named 'onnxconverter_common'
Traceback (most recent call last):
  File "C:\RJ\Abao\Open-LLM-VTuber\start_webui.py", line 41, in <module>
    main()
  File "C:\RJ\Abao\Open-LLM-VTuber\start_webui.py", line 35, in main
    subprocess.run(run_cmd, shell=True, check=True)
  File "C:\Users\29642\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'call C:\RJ\Abao\Open-LLM-VTuber\conda\Scripts\activate.bat open_llm_vtuber && python server.py' returned non-zero exit status 1.
PS C:\RJ\Abao\Open-LLM-VTuber>
```

**Comment by t41372** [comment]
可以试试执行 `activate_conda.py` 之后用 `pip install onnxconverter_common` 试试吗？

**Comment by xfrqh** [comment]
还是不行。
```shell
PS C:\RJ\Abao\Open-LLM-VTuber> C:\RJ\Abao\Open-LLM-VTuber\activate_conda.py
PS C:\RJ\Abao\Open-LLM-VTuber>
                               pip install onnxconverter_common
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: onnxconverter_common in c:\users\29642\appdata\local\programs\python\python311\lib\site-packages (1.14.0)
Requirement already satisfied: numpy in c:\users\29642\appdata\local\programs\python\python311\lib\site-packages (from onnxconverter_common) (2.1.0)
Requirement already satisfied: onnx in c:\users\29642\appdata\local\programs\python\python311\lib\site-packages (from onnxconverter_common) (1.17.0)
Requirement already satisfied: packaging in c:\users\29642\appdata\local\programs\python\python311\lib\site-packages (from onnxconverter_common) (24.1)
Requirement already satisfied: protobuf==3.20.2 in c:\users\29642\appdata\local\programs\python\python311\lib\site-packages (from onnxconverter_common) (3.20.2)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\RJ\Abao\Open-LLM-VTuber> python start_webui.py
2024-12-22 18:05:19.157 | INFO     | __main__:__init__:38 - t41372/Open-LLM-VTuber, version 0.5.2
2024-12-22 18:05:19.158 | INFO     | __main__:__init__:59 - Preloading ASR and TTS models...
2024-12-22 18:05:19.158 | INFO     | __main__:__init__:60 - Using: FunASR
2024-12-22 18:05:19.158 | INFO     | __main__:__init__:63 - Using: edgeTTS
Traceback (most recent call last):
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 598, in <module>
    server = WebSocketServer(open_llm_vtuber_main_config=config)
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 68, in __init__
    self.model_manager.initialize_models()
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 474, in initialize_models
    self._init_asr()
  File "C:\RJ\Abao\Open-LLM-VTuber\server.py", line 484, in _init_asr
    self.cache.set("asr", ASRFactory.get_asr_system(asr_model, **asr_config))
  File "C:\RJ\Abao\Open-LLM-VTuber\asr\asr_factory.py", line 26, in get_asr_system
    from .fun_asr import VoiceRecognition as FunASR
  File "C:\RJ\Abao\Open-LLM-VTuber\asr\fun_asr.py", line 6, in <module>
    from funasr import AutoModel
  File "C:\RJ\Abao\Open-LLM-VTuber\conda\envs\open_llm_vtuber\lib\site-packages\funasr\__init__.py", line 39, in <module>
    from funasr.auto.auto_model import AutoModel
  File "C:\RJ\Abao\Open-LLM-VTuber\conda\envs\open_llm_vtuber\lib\site-packages\funasr\auto\auto_model.py", line 30, in <module>
    from funasr.utils import export_utils
  File "C:\RJ\Abao\Open-LLM-VTuber\conda\envs\open_llm_vtuber\lib\site-packages\funasr\utils\export_utils.py", line 5, in <module>
    from onnxconverter_common import float16
ModuleNotFoundError: No module named 'onnxconverter_common'
Traceback (most recent call last):
  File "C:\RJ\Abao\Open-LLM-VTuber\start_webui.py", line 41, in <module>
    main()
  File "C:\RJ\Abao\Open-LLM-VTuber\start_webui.py", line 35, in main
    subprocess.run(run_cmd, shell=True, check=True)
  File "C:\Users\29642\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'call C:\RJ\Abao\Open-LLM-VTuber\conda\Scripts\activate.bat open_llm_vtuber && python server.py' returned non-zero exit status 1.
PS C:\RJ\Abao\Open-LLM-VTuber>
```

**Comment by t41372** [comment]
我研究一下看能不能复现

**Comment by t41372** [comment]
复现大成功... 该死，FunASR 又改了什么东西... 我去看看...

**Comment by t41372** [comment]
这样，你 ASR 可以改用 sherpa-onnx 的 SenseVoiceSmall 模型，先别用 FunASR 了

**Comment by xfrqh** [comment]
怎么操作？我会一点python。

**Comment by t41372** [comment]
可以看看 README 里面写的关于 sherpa onnx 的部分

**Comment by t41372** [comment]
我用 `activate_conda.py` 激活虚拟环境之后用 `pip install onnxconverter_common` 后成功了，如果你还想用 FunASR 的话可以试试，我等会再测试一下，修改一下脚本，把这玩意儿加进去。
FunASR 怎么老是在包里面引用 `requirements` 里面没写的依赖，还不写文档，改了还没提... 真是草了
我计划之后版本预设 ASR 切换成 sherpa onnx + SenseVoiceSmall 模型的组合，感觉奇奇怪怪的问题会少一些。

**Comment by xfrqh** [comment]
我认为我犯了一个细节上的错误：
应该用`python c:/xxx/activate_conda.py`，而不是`c:/xxx/activate_conda.py`来激活conda。

我安装了 AzureASR ，并修改配置。现在已经成功开启WebUI
